#!/usr/bin/env python3
import time
import skilstak.colors as c
def hello():
    print(c.clear + c.blue + "hello " + c.red + "world" + c.red + c.reset)

def rand():
    while True:
        print(c.multi("Hello World") + c.reset)
        time.sleep(.2)
        print(c.clear)

    if __name__ == '__main__':
        print(c.clear)
        while True:
            print(c.rc() + "Hello World" + c.reset)

hello()
time.sleep(1)
rand()

