#!/usr/bin/env python3
import time
import skilstak.colors as c
import sys
def plane():
    """clears the screen and prints 'Hello World'"""
    print(c.clear + c.blue + "hello " + c.red + "world" + c.red + c.reset)

def rand():
    for ran in range(10):
        print(c.multi("Hello World") + c.reset)
        time.sleep(.2)
        print(c.clear)

def color():
    while True:
        print(c.multi("Hello World") + c.reset , end=' ')
            
def hello(kind='plane'):
    try:        
        if kind == 'color':
            color()
        elif kind.startswith('m'):
            rand()
        elif kind.startswith('r'):
            color()
        else:
            plane()
    except KeyboardInterrupt:
            return

if __name__ == '__main__':
    if len(sys.argv) == 1:
        hello()
    else:
        hello(sys.argv[1])
